        1. &u      =  e. F9C
        2. &j      =  b. F9E
        3. pj      =  b. F9E
        4. *pj     =  c. 35
        5. i       =  g. unspecified (60)
        6. pi      =  e. F9C
        7. *pi     =  g. unspecified (25)
        8. (pi+2)  =  i. F9E
        9. (*pi+2) =  g. unspecified (27)
       10.*(pi+2)  =  c. 35
